Traceback (most recent call last):
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/nbclient/client.py", line 604, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/m/anaconda3/envs/tf/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/nbclient/client.py", line 811, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/nbclient/client.py", line 628, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/m/anaconda3/envs/tf/lib/python3.6/site-packages/nbclient/client.py", line 679, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 100 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
# HIDE CODE

with varying_intercept_slope:    
    varying_intercept_slope_trace = pm.sample(1000, tune=6000, target_accept=0.99, random_seed=RANDOM_SEED)
-------------------

